"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {LayoutDashboard,ClipboardList,Users,Shirt,Wallet,Plus,Search,ArrowUpRight,Clock3,CheckCircle2,PackageCheck,RefreshCw,Menu,X,ChevronRight,CalendarDays,Droplets,TrendingUp,AlertCircle,Download} from "lucide-react";
type Customer={id:number;name:string;phone:string;email:string;address:string;created_at:string};
type Service={id:number;name:string;category:string;unit:string;price_cents:number;turnaround_hours:number;active:number};
type Order={id:number;reference:string;customer_id:number;customer_name:string;customer_phone:string;service_id:number;service_name:string;unit:string;quantity:number;total_cents:number;paid_cents:number;status:string;payment_method:string;notes:string;created_at:string;due_at:string;completed_at:string|null};
type Payment={id:number;reference:string;amount_cents:number;method:string;created_at:string};
type Data={customers:Customer[];services:Service[];orders:Order[];payments:Payment[]};
const empty:Data={customers:[],services:[],orders:[],payments:[]};
const peso=(v:number)=>"₱"+(v/100).toLocaleString("en-PH",{minimumFractionDigits:2,maximumFractionDigits:2});
const date=(v:string)=>new Date(v).toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"});
const dateTime=(v:string)=>new Date(v).toLocaleString("en-PH",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
const steps=["Received","Washing","Drying","Ready","Collected"];
const methods=["Cash","GCash","Card","Bank transfer"];
function badge(status:string){return <span className={'badge '+status.toLowerCase()}><span className="badge-dot"/>{status}</span>}
export default function Home(){
 const [tab,T]=useState("Dashboard"),[data,D]=useState<Data>(empty),[search,S]=useState(""),[modal,M]=useState(""),[form,F]=useState<Record<string,string>>({}),[busy,B]=useState(false),[error,E]=useState(""),[toast,A]=useState(""),[selected,Q]=useState<Order|null>(null),[nav,N]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/laundry?search='+encodeURIComponent(search));const j=await r.json() as Data & {error?:string};if(!r.ok)throw Error(j.error);D(j)}catch(e){E(e instanceof Error?e.message:"Could not load data.")}},[search]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!toast)return;const h=setTimeout(()=>A(""),4500);return()=>clearTimeout(h)},[toast]);
 const post=async(body:Record<string,unknown>)=>{B(true);E("");try{const r=await fetch('/api/laundry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json() as {error?:string;message?:string};if(!r.ok)throw Error(j.error||"Request failed.");A(j.message||"Saved.");M("");F({});await load();return true}catch(e){E(e instanceof Error?e.message:"Request failed.");return false}finally{B(false)}};
 const show=(name:string,order?:Order)=>{E("");F({});Q(order||null);M(name)};
 const active=data.orders.filter(o=>!['Collected','Cancelled'].includes(o.status));
 const outstanding=data.orders.filter(o=>o.status!=="Cancelled").reduce((x,o)=>x+o.total_cents-o.paid_cents,0);
 const collected=data.payments.reduce((x,p)=>x+p.amount_cents,0);
 const overdue=active.filter(o=>new Date(o.due_at)<new Date()).length;
 const filtered=data.orders;
 const current=data.orders.find(o=>o.id===selected?.id)||selected;
 const submit=async()=>{if(modal==="customer")await post({action:"customer",...form});if(modal==="service")await post({action:"service",name:form.name,category:form.category,unit:form.unit,priceCents:Math.round(Number(form.price)*100),turnaroundHours:Number(form.hours)});if(modal==="order")await post({action:"order",customerId:Number(form.customerId),serviceId:Number(form.serviceId),quantity:Number(form.quantity),paidCents:Math.round(Number(form.paid||0)*100),paymentMethod:form.method||"Cash",notes:form.notes||""});if(modal==="payment"&&current)await post({action:"payment",id:current.id,amountCents:Math.round(Number(form.amount)*100),method:form.method||"Cash"})};
 const exportCSV=()=>{const lines=[['Reference','Customer','Phone','Service','Quantity','Status','Total PHP','Paid PHP','Created','Due'],...data.orders.map(o=>[o.reference,o.customer_name,o.customer_phone,o.service_name,String(o.quantity),o.status,(o.total_cents/100).toFixed(2),(o.paid_cents/100).toFixed(2),o.created_at,o.due_at])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\r\n')],{type:'text/csv'}));a.download='linenloop-orders.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 const navItems=[{name:"Dashboard",icon:LayoutDashboard},{name:"Orders",icon:ClipboardList},{name:"Customers",icon:Users},{name:"Services",icon:Shirt},{name:"Payments",icon:Wallet}];
 return <div className="shell"><aside className={'sidebar '+(nav?'open':'')}><div className="brand"><span className="brand-mark"><Droplets size={23} fill="currentColor"/></span><span>Linen<span className="brand-accent">Loop</span><small>LAUNDRY STUDIO</small></span></div><div className="sidebar-label">WORKSPACE</div><nav>{navItems.map(({name,icon:Icon})=><button key={name} className={'nav-item '+(tab===name?'active':'')} onClick={()=>{T(name);N(false);E("")}}><Icon size={19}/>{name}{tab===name&&<ChevronRight size={15} className="nav-arrow"/>}</button>)}</nav><div className="sidebar-bottom"><div className="side-card"><span className="side-card-icon"><Shirt size={20}/></span><strong>Keep things moving</strong><p>Every garment has a journey. Stay on top of every order.</p></div><div className="side-user"><span className="avatar">LL</span><span><strong>Operations desk</strong><small>LinenLoop workspace</small></span></div></div></aside>
 <main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>N(!nav)} aria-label="Toggle menu">{nav?<X/>:<Menu/>}</button><div className="crumb">Workspace <ChevronRight size={15}/> <strong>{tab}</strong></div><div className="top-actions"><span className="today"><CalendarDays size={16}/>{new Date().toLocaleDateString('en-PH',{weekday:'short',month:'short',day:'numeric',year:'numeric'})}</span><button className="icon-btn" title="Refresh" onClick={()=>void load()}><RefreshCw size={18}/></button><span className="avatar small">LL</span></div></header>
 <div className="content"><div className="page-heading"><div><span className="eyebrow">LAUNDRY OPERATIONS / {tab.toUpperCase()}</span><h1>{tab==='Dashboard'?"Good day, team.":tab}</h1><p>{tab==='Dashboard'?"Here's what's happening across your laundry floor today.":tab==='Orders'?"Track every garment from drop-off to pickup.":tab==='Customers'?"The people behind every fresh start.":tab==='Services'?"Manage your offerings and turnaround times.":"A clear view of payments and balances."}</p></div><div className="heading-actions">{tab==='Orders'&&<button className="secondary-btn" onClick={exportCSV}><Download size={17}/> Export CSV</button>}{tab==='Orders'&&<button className="primary-btn" onClick={()=>show('order')}><Plus size={18}/> New order</button>}{tab==='Customers'&&<button className="primary-btn" onClick={()=>show('customer')}><Plus size={18}/> Add customer</button>}{tab==='Services'&&<button className="primary-btn" onClick={()=>show('service')}><Plus size={18}/> Add service</button>}</div></div>
 {error&&!modal&&<div className="error-banner"><AlertCircle size={17}/>{error}<button onClick={()=>E("")}>Dismiss</button></div>}
 {tab==='Dashboard'&&<><div className="hero-panel"><div><span className="hero-kicker"><span className="live-dot"/> YOUR OPERATIONS AT A GLANCE</span><h2>Fresh days begin here.</h2><p>From the first drop-off to the final pickup, keep every order moving beautifully.</p><button onClick={()=>show('order')} className="hero-btn"><Plus size={18}/> Create new order <ArrowUpRight size={17}/></button></div><div className="hero-art" aria-hidden="true"><div className="art-ring ring-one"/><div className="art-ring ring-two"/><div className="art-center"><Shirt size={94} strokeWidth={1.25}/></div><span className="art-spark sparkle-one">✦</span><span className="art-spark sparkle-two">✧</span><span className="art-spark sparkle-three">✦</span></div></div>
 <div className="stats"><Metric label="Active orders" value={String(active.length)} hint="In the workflow" icon={<ClipboardList size={21}/>} theme="mint"/><Metric label="Ready for pickup" value={String(data.orders.filter(o=>o.status==='Ready').length)} hint="Awaiting collection" icon={<PackageCheck size={21}/>} theme="blue"/><Metric label="Payments received" value={peso(collected)} hint="All recorded payments" icon={<TrendingUp size={21}/>} theme="peach"/><Metric label="Outstanding" value={peso(outstanding)} hint={`${overdue} overdue order${overdue===1?'':'s'}`} icon={<Wallet size={21}/>} theme="violet"/></div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><span className="mini-label">WORKFLOW</span><h3>Recent orders</h3></div><button className="text-link" onClick={()=>T('Orders')}>View all <ArrowUpRight size={16}/></button></div>{data.orders.length?<div className="recent-list">{data.orders.slice(0,6).map(o=><button key={o.id} className="recent-row" onClick={()=>show('detail',o)}><span className="order-icon"><Shirt size={20}/></span><span className="recent-main"><strong>{o.customer_name}</strong><small>{o.service_name} · {o.reference}</small></span><span className="recent-right">{badge(o.status)}<small>{peso(o.total_cents)}</small></span></button>)}</div>:<Empty text="No orders yet. Create the first order to get started."/>}</section><section className="panel activity"><div className="panel-heading"><div><span className="mini-label">DAILY PULSE</span><h3>At a glance</h3></div><Clock3 size={19} color="#91a0aa"/></div><div className="pulse-list">{[{label:"Received",count:data.orders.filter(x=>x.status==='Received').length,color:"#7bc7ae"},{label:"Washing",count:data.orders.filter(x=>x.status==='Washing').length,color:"#88a6e9"},{label:"Drying",count:data.orders.filter(x=>x.status==='Drying').length,color:"#efbb7a"},{label:"Ready",count:data.orders.filter(x=>x.status==='Ready').length,color:"#a68dd5"}].map(x=><div className="pulse-row" key={x.label}><span className="pulse-dot" style={{background:x.color}}/><strong>{x.label}</strong><span className="pulse-bar"><i style={{width:`${Math.max(5,Math.min(100,x.count/Math.max(1,active.length)*100))}%`,background:x.color}}/></span><b>{x.count}</b></div>)}</div><div className="activity-foot"><CheckCircle2 size={18}/> {data.orders.filter(o=>o.status==='Collected').length} orders completed all time</div></section></div></>}
 {tab==='Orders'&&<section className="panel table-panel"><div className="table-tools"><div className="searchbox"><Search size={18}/><input placeholder="Search reference, name or phone..." value={search} onChange={e=>S(e.target.value)}/></div><span className="table-count">{filtered.length} orders</span></div><div className="table-scroll"><table><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>SERVICE</th><th>DATE / DUE</th><th>STATUS</th><th>TOTAL / BALANCE</th><th></th></tr></thead><tbody>{filtered.map(o=><tr key={o.id} onClick={()=>show('detail',o)}><td><strong className="reference">{o.reference}</strong><small>#{String(o.id).padStart(4,'0')}</small></td><td><strong>{o.customer_name}</strong><small>{o.customer_phone}</small></td><td><strong>{o.service_name}</strong><small>{o.quantity} {o.unit}</small></td><td><strong>{date(o.created_at)}</strong><small>Due {date(o.due_at)}</small></td><td>{badge(o.status)}</td><td><strong>{peso(o.total_cents)}</strong><small className={o.total_cents>o.paid_cents?'balance':''}>{o.total_cents===o.paid_cents?'Paid':peso(o.total_cents-o.paid_cents)+' due'}</small></td><td><ArrowUpRight size={18} color="#91a1a9"/></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="No matching orders. Create an order to start tracking."/>}</section>}
 {tab==='Customers'&&<section className="panel table-panel"><div className="table-tools"><h3>Customer directory</h3><span className="table-count">{data.customers.length} customers</span></div><div className="table-scroll"><table><thead><tr><th>CUSTOMER</th><th>CONTACT</th><th>ADDRESS</th><th>ORDERS</th><th>JOINED</th></tr></thead><tbody>{data.customers.map(c=><tr key={c.id}><td><span className="customer-cell"><span className="customer-avatar">{c.name.slice(0,2).toUpperCase()}</span><strong>{c.name}</strong></span></td><td><strong>{c.phone}</strong><small>{c.email||'No email'}</small></td><td>{c.address||'—'}</td><td><span className="count-pill">{data.orders.filter(o=>o.customer_id===c.id).length}</span></td><td>{date(c.created_at)}</td></tr>)}</tbody></table></div>{!data.customers.length&&<Empty text="No customers yet. Add one to create an order."/>}</section>}
 {tab==='Services'&&<><div className="section-note">Set your pricing and turnaround. Inactive services stay in history but cannot be selected for new orders.</div><div className="service-grid">{data.services.map(s=><div className="service-card" key={s.id}><div className="service-card-top"><span className="service-icon"><Shirt size={24}/></span><span className={'service-state '+(!s.active?'off':'')}>{s.active?'Active':'Inactive'}</span></div><span className="mini-label">{s.category.toUpperCase()}</span><h3>{s.name}</h3><div className="service-info"><span><Clock3 size={15}/> {s.turnaround_hours}h turnaround</span><span>Per {s.unit}</span></div><div className="service-bottom"><div><strong>{peso(s.price_cents)}</strong><small> / {s.unit}</small></div><button disabled={busy} onClick={()=>void post({action:'serviceStatus',id:s.id,active:s.active?0:1})}>{s.active?'Deactivate':'Activate'}</button></div></div>)}</div>{!data.services.length&&<div className="empty-start"><span className="service-icon"><Shirt/></span><h3>Start with your services</h3><p>Load six ready-to-use services or add your own to begin taking orders.</p><button className="primary-btn" onClick={()=>void post({action:'seed'})}>Load sample services <ArrowUpRight size={17}/></button></div>}</>}
 {tab==='Payments'&&<><div className="stats two-stats"><Metric label="Payments received" value={peso(collected)} hint={`${data.payments.length} transactions`} icon={<TrendingUp size={21}/>} theme="mint"/><Metric label="Outstanding balances" value={peso(outstanding)} hint="Across active and completed orders" icon={<Wallet size={21}/>} theme="peach"/></div><section className="panel table-panel"><div className="table-tools"><h3>Payment activity</h3><span className="table-count">{data.payments.length} recent transactions</span></div><div className="table-scroll"><table><thead><tr><th>ORDER</th><th>METHOD</th><th>DATE</th><th>AMOUNT</th></tr></thead><tbody>{data.payments.map(p=><tr key={p.id}><td><strong className="reference">{p.reference}</strong></td><td>{p.method}</td><td>{dateTime(p.created_at)}</td><td><strong className="positive">+{peso(p.amount_cents)}</strong></td></tr>)}</tbody></table></div>{!data.payments.length&&<Empty text="Payments will appear here as you record them."/>}</section></>}
 <footer>© 2026 LinenLoop · Fresh thinking for your laundry business.</footer></div></main>
 {toast&&<div className="toast"><CheckCircle2 size={19}/>{toast}<button onClick={()=>A("")}>×</button></div>}
 {modal&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)M("")}}><div className="dialog"><div className="dialog-head"><div><span className="mini-label">LINENLOOP WORKSPACE</span><h2>{modal==='order'?'Create new order':modal==='customer'?'Add customer':modal==='service'?'Add service':modal==='payment'?'Record payment':'Order details'}</h2></div><button className="close" onClick={()=>M("")} aria-label="Close"><X size={21}/></button></div>{error&&<div className="form-error">{error}</div>}
 {modal==='customer'&&<div className="fields"><Field label="Full name *" value={form.name} onChange={v=>F({...form,name:v})} placeholder="Maria Santos"/><Field label="Phone number *" value={form.phone} onChange={v=>F({...form,phone:v})} placeholder="0917 123 4567"/><Field label="Email address" value={form.email} onChange={v=>F({...form,email:v})} placeholder="maria@example.com"/><Field label="Address" value={form.address} onChange={v=>F({...form,address:v})} placeholder="Street, city"/></div>}
 {modal==='service'&&<div className="fields"><Field label="Service name *" value={form.name} onChange={v=>F({...form,name:v})} placeholder="Wash & Fold"/><Field label="Category *" value={form.category} onChange={v=>F({...form,category:v})} placeholder="Laundry"/><Field label="Unit *" value={form.unit} onChange={v=>F({...form,unit:v})} placeholder="kg, piece, or pair"/><Field label="Price per unit (₱) *" type="number" value={form.price} onChange={v=>F({...form,price:v})} placeholder="120"/><Field label="Turnaround (hours) *" type="number" value={form.hours} onChange={v=>F({...form,hours:v})} placeholder="24"/></div>}
 {modal==='order'&&<div className="fields"><label className="field">Customer *<select value={form.customerId||''} onChange={e=>F({...form,customerId:e.target.value})}><option value="">Select a customer</option>{data.customers.map(c=><option key={c.id} value={c.id}>{c.name} — {c.phone}</option>)}</select></label><label className="field">Service *<select value={form.serviceId||''} onChange={e=>F({...form,serviceId:e.target.value})}><option value="">Select a service</option>{data.services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name} · {peso(s.price_cents)}/{s.unit}</option>)}</select></label><Field label="Quantity *" type="number" value={form.quantity} onChange={v=>F({...form,quantity:v})} placeholder="3.5"/><Field label="Initial payment (₱)" type="number" value={form.paid} onChange={v=>F({...form,paid:v})} placeholder="0.00"/><label className="field">Payment method<select value={form.method||'Cash'} onChange={e=>F({...form,method:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></label><Field label="Notes" value={form.notes} onChange={v=>F({...form,notes:v})} placeholder="Special care instructions"/>{form.serviceId&&form.quantity&&<div className="price-preview">Estimated total <strong>{peso(Math.round((data.services.find(s=>s.id===Number(form.serviceId))?.price_cents||0)*Number(form.quantity)))}</strong></div>}</div>}
 {modal==='payment'&&current&&<><div className="payment-context">{current.reference} · {current.customer_name}<strong>Balance: {peso(current.total_cents-current.paid_cents)}</strong></div><div className="fields"><Field label="Amount (₱) *" type="number" value={form.amount} onChange={v=>F({...form,amount:v})} placeholder={((current.total_cents-current.paid_cents)/100).toFixed(2)}/><label className="field">Payment method<select value={form.method||'Cash'} onChange={e=>F({...form,method:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></label></div></>}
 {modal==='detail'&&current&&<div className="detail"><div className="detail-title"><div><span className="mini-label">{current.reference}</span><h3>{current.customer_name}</h3><span>{current.customer_phone}</span></div>{badge(current.status)}</div><div className="detail-pairs"><div><small>Service</small><strong>{current.service_name}</strong></div><div><small>Quantity</small><strong>{current.quantity} {current.unit}</strong></div><div><small>Received</small><strong>{dateTime(current.created_at)}</strong></div><div><small>Expected by</small><strong>{dateTime(current.due_at)}</strong></div><div><small>Payment method</small><strong>{current.payment_method}</strong></div><div><small>Notes</small><strong>{current.notes||'—'}</strong></div></div><div className="total-box"><span>Total <strong>{peso(current.total_cents)}</strong></span><span>Paid <strong>{peso(current.paid_cents)}</strong></span><span>Balance <strong>{peso(current.total_cents-current.paid_cents)}</strong></span></div><div className="progress-track">{steps.map((x,i)=><div key={x} className={'progress-step '+(steps.indexOf(current.status)>=i?'done':'')}><span>{i+1}</span><small>{x}</small></div>)}</div><div className="detail-actions">{current.total_cents>current.paid_cents&&current.status!=='Cancelled'&&<button className="secondary-btn" onClick={()=>show('payment',current)}><Wallet size={17}/> Record payment</button>}{!['Collected','Cancelled'].includes(current.status)&&<button className="primary-btn" disabled={busy} onClick={()=>void post({action:'status',id:current.id,status:steps[steps.indexOf(current.status)+1]})}>Move to {steps[steps.indexOf(current.status)+1]} <ChevronRight size={17}/></button>}</div>{!['Collected','Cancelled'].includes(current.status)&&<button className="cancel-link" disabled={busy} onClick={()=>void post({action:'status',id:current.id,status:'Cancelled'})}>Cancel order</button>}</div>}
 {modal!=='detail'&&<div className="dialog-foot"><button className="secondary-btn" onClick={()=>M("")}>Cancel</button><button className="primary-btn" disabled={busy} onClick={()=>void submit()}>{busy?'Saving...':modal==='order'?'Create order':modal==='payment'?'Record payment':modal==='service'?'Add service':'Add customer'} <ArrowUpRight size={17}/></button></div>}</div></div>}
 </div>
}
function Metric({label,value,hint,icon,theme}:{label:string;value:string;hint:string;icon:React.ReactNode;theme:string}){return <div className="metric"><div className={'metric-icon '+theme}>{icon}</div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div>}
function Field({label,value,onChange,placeholder,type="text"}:{label:string;value?:string;onChange:(s:string)=>void;placeholder?:string;type?:string}){return <label className="field">{label}<input type={type} min={type==='number'?'0':undefined} step={type==='number'?'any':undefined} value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Empty({text}:{text:string}){return <div className="empty"><span><ClipboardList size={27}/></span><p>{text}</p></div>}
