import {env} from "cloudflare:workers";
type B={action?:string;[key:string]:unknown};
const db=()=>{if(!env.DB)throw Error("Database unavailable");return env.DB};
const s=(v:unknown,n=200)=>typeof v==="string"?v.trim().slice(0,n):"";
const n=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?v:NaN;
const bad=(error:string,status=400)=>Response.json({error},{status});
const fail=(e:unknown)=>{console.error(e);return bad(e instanceof Error&&e.message.includes("UNIQUE constraint")?"That record already exists.":"Request failed. Please retry.",500)};
const statuses=["Received","Washing","Drying","Ready","Collected","Cancelled"];
export async function GET(request:Request){try{const d=db(),q=s(new URL(request.url).searchParams.get("search"),80),like=`%${q}%`;
const [customers,services,orders,payments]=await d.batch([
d.prepare("SELECT * FROM customers ORDER BY id DESC LIMIT 500"),d.prepare("SELECT * FROM services ORDER BY id"),
d.prepare("SELECT o.*,c.name AS customer_name,c.phone AS customer_phone,s.name AS service_name,s.unit FROM orders o JOIN customers c ON c.id=o.customer_id JOIN services s ON s.id=o.service_id WHERE o.reference LIKE ? OR c.name LIKE ? OR c.phone LIKE ? ORDER BY o.id DESC LIMIT 500").bind(like,like,like),
d.prepare("SELECT p.*,o.reference FROM payments p JOIN orders o ON o.id=p.order_id ORDER BY p.id DESC LIMIT 100")]);return Response.json({customers:customers.results,services:services.results,orders:orders.results,payments:payments.results})}catch(e){return fail(e)}}
export async function POST(request:Request){let b:B;try{b=await request.json() as B}catch{return bad("Invalid JSON.")}
try{const d=db(),now=new Date().toISOString();
if(b.action==="seed"){const c=await d.prepare("SELECT COUNT(*) AS count FROM services").first<{count:number}>();if(c?.count)return bad("Services already loaded.",409);await d.batch([["Wash & Fold","Laundry","kg",12000,24],["Wash & Iron","Laundry","kg",18000,36],["Dry Clean","Garments","piece",35000,48],["Comforter Care","Bedding","piece",65000,72],["Express Wash","Express","kg",22000,8],["Shoe Cleaning","Specialty","pair",45000,72]].map(x=>d.prepare("INSERT INTO services(name,category,unit,price_cents,turnaround_hours,active) VALUES(?,?,?,?,?,1)").bind(...x)));return Response.json({message:"Sample services loaded."})}
if(b.action==="customer"){const name=s(b.name,100),phone=s(b.phone,30),email=s(b.email,120),address=s(b.address,240);if(!name||phone.length<7||email&&!/^\S+@\S+\.\S+$/.test(email))return bad("Enter a name, phone and optional valid email.");await d.prepare("INSERT INTO customers(name,phone,email,address,created_at) VALUES(?,?,?,?,?)").bind(name,phone,email,address,now).run();return Response.json({message:"Customer added."},{status:201})}
if(b.action==="service"){const name=s(b.name,100),category=s(b.category,50),unit=s(b.unit,20),price=n(b.priceCents),hours=n(b.turnaroundHours);if(!name||!category||!unit||!Number.isInteger(price)||price<=0||price>1e7||!Number.isInteger(hours)||hours<1||hours>720)return bad("Enter valid service details.");await d.prepare("INSERT INTO services(name,category,unit,price_cents,turnaround_hours,active) VALUES(?,?,?,?,?,1)").bind(name,category,unit,price,hours).run();return Response.json({message:"Service added."},{status:201})}
if(b.action==="serviceStatus"){const id=n(b.id),active=n(b.active);if(!Number.isInteger(id)||![0,1].includes(active))return bad("Invalid service.");const r=await d.prepare("UPDATE services SET active=? WHERE id=?").bind(active,id).run();return r.meta.changes?Response.json({message:"Service updated."}):bad("Service not found.",404)}
if(b.action==="order"){const cid=n(b.customerId),sid=n(b.serviceId),qty=n(b.quantity),paid=n(b.paidCents),method=s(b.paymentMethod,30),notes=s(b.notes,500);if(!Number.isInteger(cid)||!Number.isInteger(sid)||!Number.isFinite(qty)||qty<=0||qty>1000||!Number.isInteger(paid)||paid<0||!["Cash","GCash","Card","Bank transfer"].includes(method))return bad("Enter valid order details.");const [c,sv]=await d.batch([d.prepare("SELECT id FROM customers WHERE id=?").bind(cid),d.prepare("SELECT * FROM services WHERE id=? AND active=1").bind(sid)]);const service=sv.results[0] as {price_cents:number;turnaround_hours:number}|undefined;if(!c.results.length||!service)return bad("Select an existing customer and active service.");const total=Math.round(service.price_cents*qty);if(paid>total)return bad("Payment exceeds total.");const ref="LL-"+crypto.randomUUID().slice(0,8).toUpperCase(),due=new Date(Date.now()+service.turnaround_hours*3600000).toISOString();const r=await d.prepare("INSERT INTO orders(reference,customer_id,service_id,quantity,total_cents,paid_cents,status,payment_method,notes,created_at,due_at) VALUES(?,?,?,?,?,?,'Received',?,?,?,?)").bind(ref,cid,sid,qty,total,paid,method,notes,now,due).run();if(paid)await d.prepare("INSERT INTO payments(order_id,amount_cents,method,created_at) VALUES(?,?,?,?)").bind(r.meta.last_row_id,paid,method,now).run();return Response.json({message:`Order ${ref} created.`,reference:ref},{status:201})}
if(b.action==="status"){const id=n(b.id),status=s(b.status,30);if(!Number.isInteger(id)||!statuses.includes(status))return bad("Invalid status.");const old=await d.prepare("SELECT status FROM orders WHERE id=?").bind(id).first<{status:string}>();if(!old)return bad("Order not found.",404);const transitions:Record<string,string[]>={Received:["Washing","Cancelled"],Washing:["Drying","Cancelled"],Drying:["Ready","Cancelled"],Ready:["Collected","Cancelled"],Collected:[],Cancelled:[]};if(!transitions[old.status]?.includes(status))return bad(`Cannot change ${old.status} to ${status}.`,409);const r=await d.prepare("UPDATE orders SET status=?,completed_at=? WHERE id=? AND status=?").bind(status,status==="Collected"?now:null,id,old.status).run();return r.meta.changes?Response.json({message:`Order moved to ${status}.`}):bad("Order changed; refresh and retry.",409)}
if(b.action==="payment"){const id=n(b.id),amount=n(b.amountCents),method=s(b.method,30);if(!Number.isInteger(id)||!Number.isInteger(amount)||amount<=0||!["Cash","GCash","Card","Bank transfer"].includes(method))return bad("Enter valid payment.");const r=await d.prepare("UPDATE orders SET paid_cents=paid_cents+?,payment_method=? WHERE id=? AND status!='Cancelled' AND paid_cents+?<=total_cents").bind(amount,method,id,amount).run();if(!r.meta.changes)return bad("Payment exceeds balance or order is unavailable.",409);await d.prepare("INSERT INTO payments(order_id,amount_cents,method,created_at) VALUES(?,?,?,?)").bind(id,amount,method,now).run();return Response.json({message:"Payment recorded."})}
return bad("Unknown action.")
}catch(e){return fail(e)}}
